module.exports = {
  brandName: "深夜不關燈",
  panelChannelId: "1530927944594227260",
  reviewChannelId: "1502056385255444671",
  archiveChannelId: "1530915224926818404",
  workGuildInvite: "https://discord.gg/d3mMRMTFJ2",
  newcomerChannelId: "1509599184318238930",
  examinerRoles: {
    "valorant:technical": ["特戰技術審核"],
    "valorant:entertainment": ["特戰娛樂審核"],
    "apex:technical": ["APEX技術大神審核"],
    "apex:entertainment": ["APEX娛樂審核"],
    "lol:technical": ["LOL技術大神考核"],
    "lol:entertainment": ["LOL娛樂考核"],
    "delta:*": ["三角洲守護審核"],
    "naraka:*": ["絕地娛樂審核"],
    "tft:technical": ["TFT技術大神審核"],
    "tft:entertainment": ["TFT娛樂審核"],
    "overwatch:technical": ["Overwatch大神技術審核"],
    "overwatch:entertainment": ["Overwatch娛樂審核"],
    "cs2:*": ["CS審核"],
    "honor_of_kings:technical": ["王者榮耀技術審核"],
    "honor_of_kings:entertainment": ["王者榮耀娛樂審核"],
    "other:other": ["陪聊陪玩審核"],
  },
};
